### ISSUE TITLE
bin/cyclops-dashboard.jar doesnt exists

### ISSUE THREAD

**Issue by RandyBlythe0** [icclab/cyclops-dashboard#10]
bin folder is not present. do i have to build from source if yes then how do i build it? and  i am using centos-minimal 7. So how to setup it on centos-minimal. I have installed openstack and cyclops successfully and my Billing, Coin, UDR CDR Services are up and running

**Comment by piyush82** [comment]
we had to remove bin file as it was too big to upload into Github. Yes indeed, the jar has to be built from the source file.
