### ISSUE TITLE
Dashboard Whitelabel Error Page

### ISSUE THREAD

**Issue by mediumstack** [icclab/cyclops-dashboard#8]
After following the setup instructions on the master branch and starting the dashboard, I get a "Whitelabel Error Page" when browsing to the web page.

![white-label-error](https://cloud.githubusercontent.com/assets/9724368/24210967/978a4ef2-0f22-11e7-926a-7ddf862dc9a0.JPG)

In the nohup.out log I get an exception: `org.springframework.web.HttpSessionRequiredException: Expected session attribute 'username'` (full log below).
[cyclops-dashboard-master-log.txt](https://github.com/icclab/cyclops-dashboard/files/862269/cyclops-dashboard-master-log.txt)

My dashboard.conf is
[cyclops-dashboard-conf.txt](https://github.com/icclab/cyclops-dashboard/files/862268/cyclops-dashboard-conf.txt)

I have run the setup from https://github.com/icclab/cyclops-udr and my microservices are listening on the relevant ports.

Anyone know why I am getting this error?

Thanks

**Comment by ManuPerezBelmonte** [comment]
Hello Maxstack,
if you installed everything as it's supposed to be, you should be able to access the dashboard through IP:8080/login 
However, we will change this so you can access it through :8080/ and there are no more issues.

Cheers, 

Cyclops Team

**Comment by mediumstack** [comment]
Hi Manu,

Thanks for your response, after browsing to /login I was able to get into the dashboard.

I have created a pull request to assist other users when first deploying:
https://github.com/icclab/cyclops-dashboard/pull/9

Max

**Comment by ManuPerezBelmonte** [comment]
This has just been updated and you can access the dashboard through :8080/

**Comment by mediumstack** [comment]
Thanks Manu!
